"""Add incident screening fields

Revision ID: e71b6a79eb68
Revises: h9b0c1d2e3f4
Create Date: 2026-03-11 06:39:30.014351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e71b6a79eb68'
down_revision = 'h9b0c1d2e3f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE:
    # Autogenerate detected additional index/constraint diffs that we do NOT want to
    # apply as part of this fix. Keep this migration minimal and additive:
    # only add the screening/routing insight fields used by the application.
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resident_category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('system_category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('suggested_authority_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('suggested_priority', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('screening_confidence', sa.Float(), nullable=True))
        # Existing rows must have a value; use server default to avoid NOT NULL failures.
        batch_op.add_column(
            sa.Column(
                'requires_admin_review',
                sa.Boolean(),
                nullable=False,
                server_default=sa.text('false'),
            )
        )
        batch_op.add_column(sa.Column('screening_notes', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'authorities', ['suggested_authority_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'incident_categories', ['resident_category_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'incident_categories', ['system_category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('screening_notes')
        batch_op.drop_column('requires_admin_review')
        batch_op.drop_column('screening_confidence')
        batch_op.drop_column('suggested_priority')
        batch_op.drop_column('suggested_authority_id')
        batch_op.drop_column('system_category_id')
        batch_op.drop_column('resident_category_id')
    # ### end Alembic commands ###
